// بيانات تجريبية أولية تُستخدم فقط عند عدم وجود بيانات محفوظة (وضع localStorage بدون Supabase)
export const INITIAL_DATA = {
  categories: [
    {
      id: "c1",
      name: "كراتين",
    },
    {
      id: "c2",
      name: "أكياس",
    },
    {
      id: "c3",
      name: "علب بلاستيك",
    },
    {
      id: "c4",
      name: "ورق تغليف",
    },
  ],
  units: [
    {
      id: "u1",
      name: "قطعة",
      abbreviation: "قطعة",
    },
    {
      id: "u2",
      name: "كيلوجرام",
      abbreviation: "كجم",
    },
    {
      id: "u3",
      name: "متر",
      abbreviation: "م",
    },
    {
      id: "u4",
      name: "رول",
      abbreviation: "رول",
    },
    {
      id: "u5",
      name: "كرتونة",
      abbreviation: "كرتونة",
    },
  ],
  products: [
    {
      id: "p1",
      sku: "PKG-001",
      name: "كرتون مقاس A4",
      category_id: "c1",
      unit_id: "u5",
      cost_price: 12,
      sale_price: 18,
      min_stock_level: 50,
      is_active: true,
    },
    {
      id: "p2",
      sku: "PKG-002",
      name: "كيس بلاستيك شفاف 30×40",
      category_id: "c2",
      unit_id: "u1",
      cost_price: 0.5,
      sale_price: 0.9,
      min_stock_level: 200,
      is_active: true,
    },
    {
      id: "p3",
      sku: "PKG-003",
      name: "علبة بلاستيك 1 لتر",
      category_id: "c3",
      unit_id: "u1",
      cost_price: 3,
      sale_price: 5.5,
      min_stock_level: 100,
      is_active: true,
    },
    {
      id: "p4",
      sku: "PKG-004",
      name: "ورق تغليف بابل رول",
      category_id: "c4",
      unit_id: "u4",
      cost_price: 25,
      sale_price: 40,
      min_stock_level: 20,
      is_active: true,
    },
    {
      id: "p5",
      sku: "PKG-005",
      name: "كرتون مقاس كبير",
      category_id: "c1",
      unit_id: "u5",
      cost_price: 18,
      sale_price: 28,
      min_stock_level: 30,
      is_active: true,
    },
  ],
  clients: [
    {
      id: "cl1",
      name: "شركة النيل للتجارة",
      phone: "01001234567",
      email: "nile@trade.com",
      address: "القاهرة، مصر الجديدة",
      tax_number: "123456789",
      type: "company",
      is_active: true,
    },
    {
      id: "cl2",
      name: "محمد أحمد سالم",
      phone: "01112345678",
      email: "",
      address: "الجيزة، فيصل",
      tax_number: "",
      type: "retail",
      is_active: true,
    },
    {
      id: "cl3",
      name: "مصنع الأمل للغذاء",
      phone: "01223456789",
      email: "alamal@food.eg",
      address: "العاشر من رمضان",
      tax_number: "987654321",
      type: "company",
      is_active: true,
    },
  ],
  suppliers: [
    {
      id: "s1",
      name: "مصنع الكرتون الذهبي",
      phone: "01334567890",
      email: "golden@carton.eg",
      address: "السادس من أكتوبر",
      tax_number: "111222333",
      is_active: true,
    },
    {
      id: "s2",
      name: "شركة البلاستيك الحديث",
      phone: "01445678901",
      email: "modern@plastic.eg",
      address: "العبور الصناعية",
      tax_number: "444555666",
      is_active: true,
    },
  ],
  stock_levels: [
    {
      id: "sl1",
      product_id: "p1",
      quantity: 120,
    },
    {
      id: "sl2",
      product_id: "p2",
      quantity: 3500,
    },
    {
      id: "sl3",
      product_id: "p3",
      quantity: 80,
    },
    {
      id: "sl4",
      product_id: "p4",
      quantity: 15,
    },
    {
      id: "sl5",
      product_id: "p5",
      quantity: 45,
    },
  ],
  manufacturing_orders: [],
  stock_movements: [
    {
      id: "sm1",
      product_id: "p1",
      movement_type: "in",
      quantity: 200,
      unit_cost: 12,
      notes: "شراء من المورد",
      reference_type: "purchase",
      created_at: "2025-05-10",
    },
    {
      id: "sm2",
      product_id: "p2",
      movement_type: "in",
      quantity: 5000,
      unit_cost: 0.5,
      notes: "شراء من المورد",
      reference_type: "purchase",
      created_at: "2025-05-12",
    },
    {
      id: "sm3",
      product_id: "p1",
      movement_type: "out",
      quantity: 80,
      unit_cost: 12,
      notes: "بيع للعميل",
      reference_type: "sale",
      created_at: "2025-05-15",
    },
    {
      id: "sm4",
      product_id: "p4",
      movement_type: "in",
      quantity: 30,
      unit_cost: 25,
      notes: "شراء من المورد",
      reference_type: "purchase",
      created_at: "2025-05-20",
    },
    {
      id: "sm5",
      product_id: "p4",
      movement_type: "out",
      quantity: 15,
      unit_cost: 25,
      notes: "بيع للعميل",
      reference_type: "sale",
      created_at: "2025-06-01",
    },
  ],
  invoices: [
    {
      id: "inv1",
      invoice_number: "INV-2025-001",
      type: "sale",
      client_id: "cl1",
      supplier_id: null,
      invoice_date: "2025-05-15",
      due_date: "2025-06-15",
      subtotal: 1440,
      discount_amount: 0,
      tax_rate: 14,
      tax_amount: 201.6,
      total_amount: 1641.6,
      paid_amount: 1641.6,
      status: "paid",
      notes: "",
      created_at: "2025-05-15",
      items: [
        {
          id: "ii1",
          product_id: "p1",
          quantity: 80,
          unit_price: 18,
          discount_percent: 0,
          total_price: 1440,
        },
      ],
    },
    {
      id: "inv2",
      invoice_number: "INV-2025-002",
      type: "sale",
      client_id: "cl3",
      supplier_id: null,
      invoice_date: "2025-06-01",
      due_date: "2025-07-01",
      subtotal: 600,
      discount_amount: 30,
      tax_rate: 14,
      tax_amount: 79.8,
      total_amount: 649.8,
      paid_amount: 300,
      status: "partial",
      notes: "يدفع الباقي نهاية الشهر",
      created_at: "2025-06-01",
      items: [
        {
          id: "ii2",
          product_id: "p4",
          quantity: 15,
          unit_price: 40,
          discount_percent: 0,
          total_price: 600,
        },
      ],
    },
    {
      id: "inv3",
      invoice_number: "PUR-2025-001",
      type: "purchase",
      client_id: null,
      supplier_id: "s1",
      invoice_date: "2025-05-10",
      due_date: "2025-06-10",
      subtotal: 2400,
      discount_amount: 0,
      tax_rate: 14,
      tax_amount: 336,
      total_amount: 2736,
      paid_amount: 2736,
      status: "paid",
      notes: "",
      created_at: "2025-05-10",
      items: [
        {
          id: "ii3",
          product_id: "p1",
          quantity: 200,
          unit_price: 12,
          discount_percent: 0,
          total_price: 2400,
        },
      ],
    },
  ],
  payments: [
    {
      id: "pay1",
      invoice_id: "inv1",
      amount: 1641.6,
      payment_date: "2025-05-15",
      method: "cash",
      reference_number: "",
      notes: "",
    },
    {
      id: "pay2",
      invoice_id: "inv2",
      amount: 300,
      payment_date: "2025-06-01",
      method: "bank_transfer",
      reference_number: "TRF-001",
      notes: "",
    },
    {
      id: "pay3",
      invoice_id: "inv3",
      amount: 2736,
      payment_date: "2025-05-10",
      method: "cash",
      reference_number: "",
      notes: "",
    },
  ],
  expenses: [
    {
      id: "exp1",
      title: "إيجار المعرض - مايو",
      amount: 5000,
      expense_date: "2025-05-01",
      category: "إيجار",
      notes: "",
    },
    {
      id: "exp2",
      title: "فاتورة كهرباء",
      amount: 850,
      expense_date: "2025-05-15",
      category: "مرافق",
      notes: "",
    },
    {
      id: "exp3",
      title: "صيانة أجهزة",
      amount: 400,
      expense_date: "2025-06-02",
      category: "صيانة",
      notes: "",
    },
  ],
  employees: [
    {
      id: "emp1",
      name: "أحمد محمود",
      job_title: "محاسب",
      department: "الحسابات",
      phone: "01511223344",
      email: "ahmed@backsystem.eg",
      hire_date: "2024-02-01",
      salary: 6000,
      is_active: true,
      notes: "",
    },
    {
      id: "emp2",
      name: "سارة عبد الله",
      job_title: "مسؤولة مبيعات",
      department: "المبيعات",
      phone: "01622334455",
      email: "sara@backsystem.eg",
      hire_date: "2024-06-15",
      salary: 5500,
      is_active: true,
      notes: "",
    },
    {
      id: "emp3",
      name: "محمود علي",
      job_title: "عامل مخزن",
      department: "المخزون",
      phone: "01733445566",
      email: "",
      hire_date: "2025-01-10",
      salary: 4000,
      is_active: true,
      notes: "",
    },
  ],
  salary_payments: [
    {
      id: "sp1",
      employee_id: "emp1",
      amount: 6000,
      period_month: "2025-05",
      payment_date: "2025-05-30",
      notes: "",
      expense_id: "",
    },
    {
      id: "sp2",
      employee_id: "emp2",
      amount: 5500,
      period_month: "2025-05",
      payment_date: "2025-05-30",
      notes: "",
      expense_id: "",
    },
    {
      id: "sp3",
      employee_id: "emp3",
      amount: 4000,
      period_month: "2025-05",
      payment_date: "2025-05-30",
      notes: "",
      expense_id: "",
    },
  ],
  attendance: [
    {
      id: "att1",
      employee_id: "emp1",
      date: "2025-06-01",
      status: "present",
      notes: "",
    },
    {
      id: "att2",
      employee_id: "emp2",
      date: "2025-06-01",
      status: "present",
      notes: "",
    },
    {
      id: "att3",
      employee_id: "emp3",
      date: "2025-06-01",
      status: "absent",
      notes: "",
    },
  ],
  cash_vouchers: [
    {
      id: "cv1",
      type: "receipt",
      amount: 1500,
      voucher_date: "2025-05-20",
      party_name: "تحصيل من عميل نقدي",
      method: "cash",
      notes: "",
      created_at: "2025-05-20",
    },
    {
      id: "cv2",
      type: "payment",
      amount: 300,
      voucher_date: "2025-06-03",
      party_name: "مصاريف نقل بضاعة",
      method: "cash",
      notes: "",
      created_at: "2025-06-03",
    },
  ],
};
